# Generated by Django 6.0.7 on 2026-07-28 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom unique de la catégorie.', max_length=120, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, help_text="Identifiant URL. Généré automatiquement à partir du nom s'il est vide.", max_length=140, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Description optionnelle de la catégorie.', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, help_text="Identifiant URL unique. Généré automatiquement à partir du titre s'il est vide.", max_length=280, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(help_text="Résumé court affiché dans les listes d'articles.", verbose_name='Extrait')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('featured_image', models.ImageField(help_text="Image principale de l'article.", upload_to='blog/posts/featured/', verbose_name='Image à la une')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', help_text='Brouillon ou publié.', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, help_text='Afficher cet article en position privilégiée.', verbose_name='Mis en avant')),
                ('views', models.PositiveIntegerField(default=0, help_text="Nombre de consultations de l'article.", verbose_name='Vues')),
                ('published_at', models.DateTimeField(blank=True, help_text='Date de publication. Renseignée automatiquement lors de la première publication.', null=True, verbose_name='Publié le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/posts/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, help_text="Légende optionnelle de l'image.", max_length=255, verbose_name='Légende')),
                ('order', models.PositiveIntegerField(default=0, help_text="Position d'affichage (0 = première).", verbose_name='Ordre')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post', verbose_name='Article')),
            ],
            options={
                'verbose_name': "Image d'article",
                'verbose_name_plural': "Images d'article",
                'ordering': ['order', 'id'],
            },
        ),
    ]
